baseurl: "/sme-ma-blog"
url: "https://j-mat2026.github.io"

markdown: kramdown

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
